const Erros = {
    ACESSO_NEGADO: 'ACESSO_NEGADO',
    USUARIO_JA_EXISTE: 'USUARIO_JA_EXISTE',
    USUARIO_NAO_EXISTE: 'USUARIO_NÃO_EXISTE',
    SENHA_INVALIDA: 'SENHA_INVALIDA'
} as const;

export default Erros;